name: 'Slack Notification'
description: 'Notify a channel slack about CI/CD jobs'
inputs:
  webhook_slack:
    description: 'Url of your slack app or webhook'
    required: true
  channel_name:
    description: 'Name of the channel to send notification'
    required: true
  build_status:
    description: 'Status of the build job'
    required: true
  deploy_status:
    description: 'Status of the deploy job'
    required: true
  branch_name:
    description: 'Name of the branch you want to restrict'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.webhook_slack }}
    - ${{ inputs.channel_name }}
    - ${{ inputs.build_status }}
    - ${{ inputs.deploy_status }}
    - ${{ inputs.branch_name }}

